### ISSUE TITLE
flyway 的存储

### ISSUE THREAD

**Issue by hellojukay** [cd-in-practice/flywaydb-example#1]
个人建议。flyway 的数据脚本应该跟着代码走，和代码一起打包包程序中，并且代码仓库应该包含flyway各个版本的所有sql,程序启动自动完成建表，程序升级，自动完成升级数据库。这个不应该有其它工具来执行。

**Comment by hellojukay** [comment]
flyway 有提供 maven 的插件，这种 migrate 的思想在其它的语言和框架中都存在，比如 golang ,rust.

**Comment by zacker330** [comment]
> 个人建议。flyway 的数据脚本应该跟着代码走，和代码一起打包包程序中，并且代码仓库应该包含flyway各个版本的所有sql,程序启动自动完成建表，程序升级，自动完成升级数据库。这个不应该有其它工具来执行。

1. 当程序是多实例的时候，多实例同时启动，同时执行所有的sql？
2. 现实很多时候，不是一个应用对应一个DB。而多个应用对应一个DB。这时，你如何处理？

**Comment by zacker330** [comment]
> flyway 有提供 maven 的插件，这种 migrate 的思想在其它的语言和框架中都存在，比如 golang ,rust.

我没有必要每种语言都要重新去学相应的构建工具的flyway插件。而且，其他语言的构建工具，真的完全支持flyway插件吗？我是打问号的。
